# Generated by Django 4.2.13 on 2024-08-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_profilesave_customprofile_langchainkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
