# Generated by Django 4.2.13 on 2024-08-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
